### PR TITLE
Refactor code blocks

### LINKED ISSUE #29: Clippy issues
Running `cargo clippy` shows many linting issues.

### PR DESCRIPTION
**Pull request by circles-png**
Fixes #29.

### CODE REVIEW

**Comment by charleslukes** [comment]
Thank you for your PR! will take a look

**Comment by charleslukes** [comment]
Hello there! 

Love the updates. 

Everything works as expected but noticed the doc tests fails 

Please run `cargo test` to check.

**Comment by circles-png** [comment]
The `find_key` method is not completely deterministic when it finds more than one item which satisfies the predicate. `HashMap<K, V>`s do not preserve their element order.

Should it be changed to return `None` when more than one item matches?

Also, the doctests in the examples at the top of the files do not actually check the output. Consider changint the `println!`s to `assert_*!`s.

**Comment by charleslukes** [comment]
Great work mate! 

I think the idea for the `find_key` is only to return the first match key. 

https://github.com/lodash/lodash/blob/main/src/findKey.ts

so it works as expected. 

Also about the doctest, you're right will change to assert.

**Pull request merged**
